/*
 * Generated by dtrace(1M).
 */

#ifndef	_ISCSI_PROFILE_H
#define	_ISCSI_PROFILE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _ISCSI_PROFILE_H */
